backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Imprint"
        name: "imprint"
        file: "content/imprint.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: 'body', widget: 'markdown' }
      - label: "Data Protection"
        name: "dataprotection"
        file: "content/dataprotection.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: 'body', widget: 'markdown' }
      - label: "Location"
        name: "location"
        file: "content/location.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Location", name: "location", widget: "map" }
          - { label: "Adress", name: "adress", widget: "string" }
          - { label: "Phone", name: "phone",  widget: "string" }
          - label: "Working Days"
            name: "workingdays"
            widget: "object"
            fields:
              - { label: Monday, name: monday, widget: string, default: "closed" }
              - { label: Tuesday, name: tuesday, widget: string, default: "closed" }
              - { label: Wednesday, name: wednesday, widget: string, default: "closed" }
              - { label: Thursday, name: thursday, widget: string, default: "closed" }
              - { label: Friday, name: friday, widget: string, default: "closed" }
              - { label: Saturday, name: saturday, widget: string, default: "closed" }
              - { label: Sunday, name: sunday, widget: string, default: "closed" }
