backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Location"
        name: "location"
        file: "content/location.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Day, name: day, widget: string}
              - { label: Time, name: time, widget: string}
