backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Location"
        name: "location"
        file: "content/location.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Opening Times"
            name: "openingtimes"
            widget: "list"
            fields:
              - { label: Day, name: day, widget: string, default: "Geschlossen"}
